[build]
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL/"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL/"

[[redirects]]
  from = "https://docs.krustlet.dev/"
  to = "https://docs.krustlet.dev/en/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
